# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:03
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerTypo', models.SmallIntegerField(choices=[(1, 'Ingenieria de Sistemas'), (2, 'Ingenieria Petroquimica'), (3, 'Ingenieria Naval'), (4, 'Enfermeria'), (5, 'Turismo'), (6, 'Economia')])),
                ('pensum', models.ImageField(upload_to=api.models.get_image_path)),
                ('turn', models.SmallIntegerField(choices=[(1, 'Diurno'), (2, 'Nocturno')])),
            ],
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDocs', models.SmallIntegerField(choices=[(1, 'WORD'), (2, 'PDF'), (3, 'Power Point')])),
                ('status', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Bloqueado')])),
                ('docs', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.get_image_path)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Bloqueado')])),
                ('description', models.CharField(max_length=100)),
                ('docs', models.CharField(max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Bloqueado')])),
            ],
        ),
        migrations.CreateModel(
            name='PppTeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeNews', models.SmallIntegerField(choices=[(1, 'Trabajo Especial de Grado'), (2, 'Practica Profesionales')])),
                ('news', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Bloqueado')])),
                ('docs', models.CharField(max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSemester', models.SmallIntegerField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Career')),
            ],
        ),
        migrations.CreateModel(
            name='TypoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typo', models.SmallIntegerField(choices=[(1, 'Estudiante'), (2, 'Profesor'), (3, 'Invitados')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image')),
            ],
        ),
        migrations.AddField(
            model_name='typouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='typoUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TypoUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AddField(
            model_name='docs',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
