# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typoCarrer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='typoUser',
            field=models.SmallIntegerField(choices=[(1, 'Estudiante'), (2, 'Profesor')], default=0),
        ),
    ]
