# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170102_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typouser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='typoUser',
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Career'),
        ),
        migrations.AlterField(
            model_name='career',
            name='careerTypo',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='TypoUser',
        ),
    ]
