# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
