# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160925_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='pensum',
            new_name='image',
        ),
    ]
