# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170104_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 15, 25, 40, 609603, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='news',
            name='privilege',
            field=models.CharField(default='', max_length=20),
        ),
    ]
