# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_career_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='imageCareer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
    ]
