# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170104_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 15, 27, 6, 435850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='privilege',
            field=models.SmallIntegerField(default=1),
        ),
    ]
