# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_career_imagecareer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
