# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
